parameters:
#    chanpp_ev_im.example.class: chanpp\EvImBundle\Example

services:
#    chanpp_ev_im.example:
#        class: %chanpp_ev_im.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
