parameters:
#    chanpp_ev_im.example.class: chanpp\EvImBundle\Example

services:
#    chanpp_ev_im.example:
#        class: %chanpp_ev_im.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    acme_user.registration.form.type:
        class: chanpp\EvImBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acme_user_registration }

    acme_user.profile.form.type:
        class: chanpp\EvImBundle\Form\EditProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acme_user_profile }
