_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

FichaProyecto:
    resource: "@chanppEvImBundle/Controller/FichaProyectoController.php"
    type: annotation

PlanEvaluacion:
    resource: "@chanppEvImBundle/Controller/PlanEvaluacionController.php"
    type: annotation

Recurso:
    resource: "@chanppEvImBundle/Controller/RecursoController.php"
    type: annotation

Evaluacion:
    resource: "@chanppEvImBundle/Controller/EvaluacionController.php"
    type: annotation

EvaluacionDirecta:
    resource: "@chanppEvImBundle/Controller/EvaluacionDirectaController.php"
    type: annotation

EvaluacionIndirecta:
    resource: "@chanppEvImBundle/Controller/EvaluacionIndirectaController.php"
    type: annotation

uploadindirecta:
    path:      /uploadindirecta
    defaults:  { _controller: chanppEvImBundle:EvaluacionIndirecta:upload }

uploaddirecta:
    path:      /uploaddirecta
    defaults:  { _controller: chanppEvImBundle:EvaluacionDirecta:upload }

linkactivity:
    path:      /linkactivity
    defaults:  { _controller: chanppEvImBundle:Evaluacion:linkactivity }

Cuestionario:
    resource: "@chanppEvImBundle/Controller/CuestionarioController.php"
    type: annotation

PreguntaAlternativa:
    resource: "@chanppEvImBundle/Controller/PreguntaAlternativaController.php"
    type: annotation

PreguntaDesarrollo:
    resource: "@chanppEvImBundle/Controller/PreguntaDesarrolloController.php"
    type: annotation

cuestionario_preview:
    path:      /preview/{id}
    defaults:  { _controller: chanppEvImBundle:Cuestionario:preview }

cuestionario_answer:
    path:      /answer/{id}
    defaults:  { _controller: chanppEvImBundle:Cuestionario:answer }

cuestionario_save_answers:
    path:      /saveanswer/{id}
    defaults:  { _controller: chanppEvImBundle:Cuestionario:save_answers }

cuestionario_change_order:
    path:      /changeorder/{id}
    defaults:  { _controller: chanppEvImBundle:Cuestionario:change_order }

cuestionario_markasdone:
    path:      /markasdone/{id}
    defaults:  { _controller: chanppEvImBundle:Cuestionario:markasdone }

Respuesta:
    resource: "@chanppEvImBundle/Controller/RespuestaController.php"
    type: annotation

cuestionario_alternativa_link:
    path:      /alternativalink/{id}
    defaults:  { _controller: chanppEvImBundle:Cuestionario:alternativa_link }

preguntaalternativa_link_save:
    path:      /alternativalinksave/{id}
    defaults:  { _controller: chanppEvImBundle:Cuestionario:alternativa_link_save }

cuestionario_desarrollo_link:
    path:      /desarrollolink/{id}
    defaults:  { _controller: chanppEvImBundle:Cuestionario:desarrollo_link }

preguntadesarrollo_link_save:
    path:      /desarrollolinksave/{id}
    defaults:  { _controller: chanppEvImBundle:Cuestionario:desarrollo_link_save }

evaluacion_mark_done:
    path:      /evaluacionmarcardone/{id}
    defaults:  { _controller: chanppEvImBundle:Evaluacion:done }

chanpp_index:
    path:      /
    defaults:  { _controller: chanppEvImBundle:Index:index }

MetodoRecoleccion:
    resource: "@chanppEvImBundle/Controller/MetodoRecoleccionController.php"
    type: annotation

CambiosPlanEvaluacion:
    resource: "@chanppEvImBundle/Controller/CambiosPlanEvaluacionController.php"
    type: annotation